<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6d4duzm\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6d4duzm/appProdProjectContainer.php') {
    touch(__DIR__.'/Container6d4duzm.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container6d4duzm\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container6d4duzm\appProdProjectContainer(array(
    'container.build_hash' => '6d4duzm',
    'container.build_id' => 'c0d7bbff',
    'container.build_time' => 1519052002,
));
