<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHzyzont\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHzyzont/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHzyzont.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHzyzont\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerHzyzont\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Hzyzont',
    'container.build_id' => 'aa647eb7',
    'container.build_time' => 1519313352,
));
